[package]
name = "erc"
version = "0.1.0"
edition = "2024_07"

[dependencies]
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.17.0" }

starknet = "2.8.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.25.0" }

[[target.starknet-contract]]
name = "erc"
sierra = true
casm = true
